### ISSUE TITLE
Adjust `/zip` and `/launch` APIs to allow more shared properties

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-creator-backend#44]
Right now the only "shared" property is `runtime` but we should allow other properties to be defined at the top level too. (In the backend they'll just get applied equally to each Capability).

This would mean changing the layout from:

```
              properties:
                name:
                  description: The application name to use for the project
                  type: string
                runtime:
                  description: The runtime to use for the project
                  type: string
                capabilities:
                  description: The capabilities to add to the project
                  type: array
                  items:
                    type: object
                    properties:
                      module:
                        type: string
```

to something like:

```
              properties:
                name:
                  description: The application name to use for the project
                  type: string
                shared:
                  description: The shared properties that get applied to each Capability
                  type: object
                  properties:
                    runtime:
                      description: The runtime to use for the project
                      type: string
                capabilities:
                  description: The capabilities to add to the project
                  type: array
                  items:
                    type: object
                    properties:
                      module:
                        type: string
```
