### ISSUE TITLE
Generated apps need health checks

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-creator-backend#72]
We need to add the necessary resources for those dynamically inside the platform generators.

(Do NOT add them manually to the templates in `resources/templates`!)

We just need a Generator that add the following to the resources:

```yaml
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
```
