### ISSUE TITLE
Support ENV vars in template from field references

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-creator-backend#83]
```
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
```
